#!/usr/bin/env bash

for DIR in $(find src/ -maxdepth 1 -mindepth 1 -type d) ; do
    pushd $DIR &> /dev/null
    if [[ -f coverage.xml ]] ; then bash <(curl -s https://codecov.io/bash) ; fi
    popd &> /dev/null
done
